### ISSUE TITLE
Not working with Akka 2.3.0-RC2's sharding functionality

### ISSUE THREAD

**Issue by dong77** [ironfish/akka-persistence-mongo#15]
Here is how I used the sharding:
```
  ClusterSharding(system).start(
    typeName = "CoreProcessor",
    entryProps = if (cluster.selfRoles.contains("normal")) Some(Props[CoreProcessor]) else None,
    idExtractor = { case msg => ("1", msg) },
    shardResolver = { case _ => "1" })
```
When I stop the actor system that runs the event sourced processor,  another actor system (that I believe tries to become a backup) raised this error:

```
[ERROR] [02/14/2014 01:49:44.104] [kio-akka.persistence.dispatchers.default-plugin-dispatcher-18] [akka://kio/user/sharding/CoreProcessorCoordinator/singleton] swallowing exception during message send
java.io.NotSerializableException: com.mongodb.ServerAddress
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1165)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1535)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1413)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1159)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1535)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1413)

```

**Comment by ironfish** [comment]
I have not been able to reproduce this error and others have confirmed cluster sharding as working so I'm going to close this issue.
