### ISSUE TITLE
could this library co-exist with reactivemongo?

### ISSUE THREAD

**Issue by sangszhou** [ironfish/akka-persistence-mongo#94]
I'm try to make a project running in cluster with the help of akka cluster sharding. 
But it report error when akka cluster sharding try to persistent state

```
[2015-07-09 23:58:28,142] ERROR[SOAClusterSystem-akka.persistence.dispatchers.default-plugin-dispatcher-76] ActorSystemImpl - Uncaught fatal error from thread [SOAClusterSystem-akka.persistence.dispatchers.default-plugin-dispatcher-76] shutting down ActorSystem [SOAClusterSystem]
java.lang.NoSuchFieldError: NONE
	at com.mongodb.casbah.WriteConcern$.<init>(WriteConcern.scala:40) ~[casbah-core_2.11-2.7.4.jar:2.7.4]
	at com.mongodb.casbah.WriteConcern$.<clinit>(WriteConcern.scala) ~[casbah-core_2.11-2.7.4.jar:2.7.4]
	at com.mongodb.casbah.BaseImports$class.$init$(Implicits.scala:162) ~[casbah-core_2.11-2.7.4.jar:2.7.4]
	at com.mongodb.casbah.Imports$.<init>(Implicits.scala:142) ~[casbah-core_2.11-2.7.4.jar:2.7.4]
	at com.mongodb.casbah.Imports$.<clinit>(Implicits.scala) ~[casbah-core_2.11-2.7.4.jar:2.7.4]
	at akka.persistence.mongo.journal.CasbahJournalHelper$class.$init$(CasbahJournalHelper.scala:27) ~[akka-persistence-mongo-casbah_2.11-0.7.5.jar:0.7.5]
	at akka.persistence.mongo.journal.CasbahJournal.<init>(CasbahJournal.scala:14) ~[akka-persistence-mongo-casbah_2.11-0.7.5.jar:0.7.5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_51]
	at java.lang.Class.newInstance(Class.java:374) ~[na:1.7.0_51]
	at akka.util.Reflect$.instantiate(Reflect.scala:45) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.actor.NoArgsReflectConstructor.produce(Props.scala:361) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.actor.Props.newActor(Props.scala:252) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) ~[akka-actor_2.11-2.3.7.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_51]
[2015-07-09 23:58:28,143] ERROR[SOAClusterSystem-akka.actor.default-dispatcher-16] OneForOneStrategy - head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420) ~[scala-library-2.11.4.jar:na]
	at scala.collection.immutable.Nil$.head(List.scala:417) ~[scala-library-2.11.4.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[akka-actor_2.11-2.3.7.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[akka-actor_2.11-2.3.7.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_51]

```

So I wrote a small toy project which involves cluster sharding and persistent and it works just fine. I researched a little bit and found that the existing project had already contains reactivemongo dependency, so my question is could this library co-exist with reactivemongo?

**Comment by ironfish** [comment]
Reactive Mongo uses it's own version of Akka which currently seems to be:

```
val akkaActor = "com.typesafe.akka" %% "akka-actor" % "2.3.6"
```

This is one of the challenges integrating. The version of Akka needs to be the same for both Reactive Mongo and the underlying Akka journal implementation. In my previous version under [Eventsourced](https://github.com/eligosource/eventsourced/tree/master/es-journal/es-journal-mongodb-reactive) I provided a Reactive Mongo option but it became too difficult keep the Akka versions in sync. 

I suspect, in your case, different Akka versions in your mixed project was the root of the problem. That said, It sounds like when your removed Reactive mongo the clustering worked so is it okay to close this issue?
